### PR TITLE
Added notebook to close #12

### LINKED ISSUE #12: Add example finding datasets that have stopped being updated

### PR DESCRIPTION
**Pull request by potto216**
Can you review the notebook? I plan create another issue for stopped data notebook that is focused on the analysis of new vs. stopped Datasets by Source, State, and AgencyFull'

### CODE REVIEW

**Review by sowdm — APPROVED** [review]
I committed some changes in 82cbd98e0056b8d9caa1bf47ea9afca3a3733dfb. A couple were just to make the code cleaner. The substantive ones was I updated the datasets removed to include more than Stanford and Muckrock.

I also added a list of TODOs that I think are worth discussing whether we want todo.

I will let you do the merge just to be sure that you are aware that I made some changes that you can review if you'd like.

**Comment by potto216** [comment]
@sowdm it looks like the latest openpolicedata library is missing the definition of the column `supplying_entity` in datasets.py. Should I write an issue for it?

**Comment by sowdm** [comment]
Does it throw an exception or warning?

**Comment by potto216** [comment]
An exception. It looks like supplying_entity' is not defined which I did not see in datasets.py
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
File ~/cjc/opd-examples/.venv_3_11_9/lib/python3.10/site-packages/pandas/core/indexes/base.py:3805, in Index.get_loc(self, key)
   3804 try:
-> 3805     return self._engine.get_loc(casted_key)
   3806 except KeyError as err:

File index.pyx:167, in pandas._libs.index.IndexEngine.get_loc()

File index.pyx:196, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:7081, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7089, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'supplying_entity'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
Cell In[3], line 12
      7 starting_all_datasets_count=all_datasets.shape[0]
      9 # Remove datasets where the data is not supplied by the agency itself
     10 # supplying_entity is only filled out in this case. Ignore one where OPD is hosting the data
     11 # OPD only hosts datasets that were released by the agency but the agency stopped.
---> 12 all_datasets = all_datasets[all_datasets['supplying_entity'].apply(lambda x: pd.isnull(x) or 'OpenPoliceData' in x)]
     13 # Remove datasets where dates don't apply
     14 all_datasets = all_datasets[all_datasets['Year']!='NONE']

File ~/cjc/opd-examples/.venv_3_11_9/lib/python3.10/site-packages/openpolicedata/deprecated/_pandas.py:67, in DeprecationHandlerDataFrame.__getitem__(self, key)
     66 def __getitem__(self, key):
---> 67     result = super().__getitem__(key)
     68     return _cast_if_necessary(result)

File ~/cjc/opd-examples/.venv_3_11_9/lib/python3.10/site-packages/pandas/core/frame.py:4102, in DataFrame.__getitem__(self, key)
   4100 if self.columns.nlevels > 1:
   4101     return self._getitem_multilevel(key)
-> 4102 indexer = self.columns.get_loc(key)
   4103 if is_integer(indexer):
   4104     indexer = [indexer]

File ~/cjc/opd-examples/.venv_3_11_9/lib/python3.10/site-packages/pandas/core/indexes/base.py:3812, in Index.get_loc(self, key)
   3807     if isinstance(casted_key, slice) or (
   3808         isinstance(casted_key, abc.Iterable)
   3809         and any(isinstance(x, slice) for x in casted_key)
   3810     ):
   3811         raise InvalidIndexError(key)
-> 3812     raise KeyError(key) from err
   3813 except TypeError:
   3814     # If we have a listlike key, _check_indexing_error will raise
   3815     #  InvalidIndexError. Otherwise we fall through and re-raise
   3816     #  the TypeError.
   3817     self._check_indexing_error(key)

KeyError: 'supplying_entity'
```

**Comment by sowdm** [comment]
What version is your OpenPoliceData? supplying _entity isn't available in the datasets table until OPD v0.9. 

I added a line to the Jupyter script that requests supplying_entity so that line will give you a pandas error for OPD versions <0.9, I think.

**Pull request merged**
